// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGjTi0KfuYu7TU9bJKbmbB30YYhBa8bs',
    appId: '1:368952527684:web:41c3d8d1ac49b5b25a2511',
    messagingSenderId: '368952527684',
    projectId: 'control-gastos-fecc9',
    authDomain: 'control-gastos-fecc9.firebaseapp.com',
    storageBucket: 'control-gastos-fecc9.firebasestorage.app',
    measurementId: 'G-9DR9QVLQ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaP1DDXWSRh3kq4GB7yuX1PG51Q7CYNgw',
    appId: '1:368952527684:android:20ad77c15455ec545a2511',
    messagingSenderId: '368952527684',
    projectId: 'control-gastos-fecc9',
    storageBucket: 'control-gastos-fecc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3mFuAM-HVyLMyKETPzgcPZAIxWAIZuEE',
    appId: '1:368952527684:ios:b978b98f9e6caea55a2511',
    messagingSenderId: '368952527684',
    projectId: 'control-gastos-fecc9',
    storageBucket: 'control-gastos-fecc9.firebasestorage.app',
    iosBundleId: 'com.example.controlGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjGjTi0KfuYu7TU9bJKbmbB30YYhBa8bs',
    appId: '1:368952527684:web:492045041b4372c75a2511',
    messagingSenderId: '368952527684',
    projectId: 'control-gastos-fecc9',
    authDomain: 'control-gastos-fecc9.firebaseapp.com',
    storageBucket: 'control-gastos-fecc9.firebasestorage.app',
    measurementId: 'G-BQGCJB3LKN',
  );
}
